### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by Genius398** [hamiecod/hamiecod#1]
Hi! i just invited you to my organisation. you can accept the invite at https://github.com/educational-websites

**Comment by hamiecod** [comment]
Hi, thanks for inviting me to your organization. I am really sorry to say that I wouldn't be able to contribute much to your organization's codebase due to time barriers.

**Comment by Genius398** [comment]
No problem! even if you can't contribute often, you will still be accepted as a part of the team

**Comment by hamiecod** [comment]
I'll join the organisation, thanks!

**Comment by Genius398** [comment]
:)

**Comment by hamiecod** [comment]
@Genius398 can you please re-invite me to the organization, I by mistake left the organisation 😓

**Comment by Genius398** [comment]
> @Genius398 can you please re-invite me to the organization, I by mistake left the organisation 😓

sure
